export const SET_CURRENT_CONTEXT = 'SET_CURRENT_CONTEXT';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const REQUEST_SAVE_SNIPPET = 'REQUEST_SAVE_SNIPPET';
export const SUCCESS_SAVE_SNIPPET = 'SUCCESS_SAVE_SNIPPET';

export const REQUEST_FETCH_SNIPPET = 'REQUEST_FETCH_SNIPPET';
export const SUCCESS_FETCH_SNIPPET = 'SUCCESS_FETCH_SNIPPET';

export const REQUEST_DELETE_SNIPPET = 'REQUEST_DELETE_SNIPPET';
export const SUCCESS_DELETE_SNIPPET = 'SUCCESS_DELETE_SNIPPET';

export const COPY_SNIPPET_CLIPBOARD = 'COPY_SNIPPET_CLIPBOARD';

export const EDIT_SNIPPET = 'EDIT_SNIPPET';

export const SELECT_NEXT_MENU_ITEM = 'SELECT_NEXT_MENU_ITEM';
export const SELECT_PREVIOUS_MENU_ITEM = 'SELECT_PREVIOUS_MENU_ITEM';

export const SET_FILTER = 'SET_FILTER';

export default {};
