dist: trusty
sudo: required
language: node_js
node_js:
        - "7"

services:
    - mongodb

# config to support bcrypt
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
