---
- name: download
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: unarchive
  unarchive:
    remote_src: yes
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/"
  become: yes

- name: copy default configuration
  copy:
    src: "{{ wordpress_install_dir }}/wp-config-sample.php"
    dest: "{{ wordpress_install_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: replace database params on configuration
  replace:
    path: "{{ wordpress_install_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: "database_name_here", value: "{{ wordpress_db }}" }
    - { regex: "username_here", value: "{{ wordpress_user }}" }
    - { regex: "password_here", value: "{{ wordpress_password }}" }
    - { regex: "localhost", value: "{{ wordpress_database_ip }}" }
  become: yes

- name: configure apache2 to serve
  template:
    src: "templates/000-default.conf.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"
  become: yes
  notify:
    - restart apache