export const AUTHENTICATE = "AUTHENTICATE";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";

export const LOGOUT = "LOGOUT";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const FETCH_STATUS = "FETCH_STATUS";
export const FETCH_STATUS_SUCCESS = "FETCH_STATUS_SUCCESS";

export const PREPARE_TASK_FORM = "PREPARE_TASK_FORM";
export const CHANGE_TASK_FORM = "CHANGE_TASK_FORM";
export const CANCEL_TASK_FORM = "CANCEL_TASK_FORM";

export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const COMPLETE_TASK_SUCCESS = "COMPLETE_TASK_SUCCESS";
export const UNCOMPLETE_TASK = "UNCOMPLETE_TASK";
export const UNCOMPLETE_TASK_SUCCESS = "UNCOMPLETE_TASK_SUCCESS";
export const POSTPONE_TASK = "POSTPONE_TASK";
export const POSTPONE_TASK_SUCCESS = "POSTPONE_TASK_SUCCESS";
export const UNPOSTPONE_TASK = "UNPOSTPONE_TASK";
export const UNPOSTPONE_TASK_SUCCESS = "UNPOSTPONE_TASK_SUCCESS";
export const SUBMIT_TASK = "SUBMIT_TASK";
export const SUBMIT_TASK_SUCCESS = "SUBMIT_TASK_SUCCESS";

export const REQUEST_FAILED = "REQUEST_FAILED";

export const ADD_ALERT = "ADD_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";
