-- frutas
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Abacate', 'unidade media', 0.4, 61.39, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Abacaxi', 'fatia media', 1.2, 122.49, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Açaí', 'unidade media', 5.0, 25.0, 61.8, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Ameixa Fresca', 'unidade media', 3.0, 111.0, 61.1, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Ameixa Preta Seca', 'unidade media', 3.0, 25.2, 60.2, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Banana com merengue Prazer sem culpa', 'porção', 0.4, 60.0, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Banana', 'unidade media', 1.0, 60.0, 55.2, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Banana Passa', 'unidade media', 0.7, 20.0, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Caqui', 'unidade media', 0.5, 84.0, 58.8, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Cereja Fresca', 'unidade media', 12.5, 85.0, 61.2, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Coco (água)', 'copo americano', 2.0, 300.0, 57.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Damasco', 'unidade media', 3.5, 123.6, 59.3, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Figo', 'unidade pequena', 2.0, 80.0, 59.2, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Geléia Comum', 'colher sobremesa', 1.2, 22.0, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Geléia Diet', 'colher sobremesa', 4.0, 400.0, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Goiaba', 'unidade pequena', 2.0, 120.0, 61.2, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Kiwi', 'unidade media', 1.5, 115.5, 70.5, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Laranja', 'unidade pequena', 1.0, 125.0, 58.8, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Maçã', 'unidade pequena', 1.0, 100.0, 59.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Mamão papaia', 'unidade media', 0.6, 153.7, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Manga', 'unidade media', 1.2, 92.2, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Melancia', 'fatia grossa', 1.0, 180.0, 57.6, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Melão', 'fatia média', 1.0, 170.0, 59.5, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Morango', 'unidade media', 20.0, 200.00, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Nectarina', 'unidade media', 2.0, 120.0, 58.8, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pêra', 'unidade grande', 0.5, 85.0, 50.2, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pêssego', 'unidade pequena', 2.0, 140.0, 60.2, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pinha', 'unidade média', 1.0, 60.0, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Polpa de Tamarindo', 'unidade', 0.7, 25.9, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Salada de fruta', 'tigela pequena', 1.0, 100.0, 58.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Serenata de amor light', 'unidade', 0.7, 25.9, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Suco de Abacaxi', 'copo de requeijão', 0.5, 125.0, 70.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Suco de Laranja', 'copo médio', 1.0, 150.0, 67.5, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Limonada', 'copo de requeijão', 1.0, 250.0, 52.5, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Suco de Maracujá', 'copo americano', 0.6, 100.0, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Suco de Melão', 'copo americano', 1.3, 197.3, 60.9, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Suco de Soja Ades', 'porção', 0.6, 123.7, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Suco de Soja Ades light', 'porção', 2.0, 400.0, 66.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Suco de Uva', 'copo de requeijão', 0.3, 98.2, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Suco light Del Vale', 'copo americano', 2.0, 300.0, 60.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Mixirica', 'unidade média', 1.0, 150.0, 66.0, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Uva Rosada', 'cacho pequeno', 1.0, 80.0, 50.4, 'fruta');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Uva Itália', 'unidade', 11.0, 88.0, 62.5, 'fruta');

-- gordura
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Amêndoa Torrada', 'unidade', 7.0, 7.0, 41.2, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Amendoim Salgado', 'unidade', 7.5, 6.8, 39.2, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Amêndoa seca', null, null, 6.8, 40.0, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Azeitona Verde Enlatada', 'unidade média', 8.5, 42.5, 39.8, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Bacon Frito Cozido grelhado', 'fatia fina', 0.5, 7.5, 43.2, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Castanha de Caju Torrada', 'unidade média', 4.5, 6.8, 38.7, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Castanha do Pará', 'unidade média', 2.0, 6.0, 39.4, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Choco Soy Diet', 'barra', 0.3, 8.4, 40.0, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Chocolate amargo', null, null, 8.4, 40.0, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Chocolate Diet Cacau Show', 'barrinha', 0.3, 9.4, 40.0, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Chocolate meio Amargo', 'unidade pequena', 0.3, 7.8, 40.0, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Chocolate Nestlé Diet', 'tablete', 0.3, 9.1, 40.0, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Creme de leite', 'colher de sopa', 1.0, 20.0, 39.1, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Manteiga', 'colher de chá', 1.0, 5.0, 35.8, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Maionese', 'colher de chá', 2.0, 10.0, 43.5, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Azeite', 'colher de sobremesa', 1.0, 5.0, 44.2, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Óleos', 'colher de sobremesa', 1.0, 5.0, 44.2, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Semente de Linhaça', 'colher de sopa', 0.2, 7.7, 40.0, 'gordura');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Tomate seco', 'unidade', 1.0, 100.0, 34.5, 'gordura');

-- leite
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Iogurte Activia', 'unidade', 1.0, 100.0, 110.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Iogurte Dan´ Up', 'pote  comercial', 0.6, 133.7, 115.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Iogurte Natural Integral', 'unidade média', 0.7, 187.0, 115.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Iogurte de leite Magro', 'copo americano', 1.2, 181.0, 115.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Iogurte light', 'pote comercial', 1.5, 302.0, 115.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Iogurte se Sabor Frutas', 'unidade média', 0.9, 109, 115.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Leite Magro', 'xícara de chá', 1.2, 274.0, 115.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Leite de Soja', 'copo de requeijão', 1.3, 348.0, 115.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Leite de soja em pó soymilke', 'porção', 1.0, 26.0, 120.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Leite Desnatado', 'copo americano', 2.1, 329.5, 115.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Leite em Pó Integral', 'colher de sopa', 3.0, 22.5, 111.6, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Leite sensy sem lactose', 'porção', 1.5, 300.0, 117.0, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Leite Integral', 'copo americano', 1.2, 150.0, 92.2, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Leite Integral', 'copo de requeijão', 1.0, 250.0, 124.2, 'leite');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Yakute', 'medida', 2.0, 160.0, 120.0, 'leite');

-- vegetal-b
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Abóbora','colher de sopa',7.0,175.0,35.0,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Alcachofra','unidade média',0.6,79.5,35.0,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Berinjela','colher de sopa',4.0,108.0,30.2,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Beterraba Cozida','fatia fina',7.5,112.5,34.9,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Beterraba','fatia média',5.0,100.0,31.0,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Beterraba Crua','colher de sopa',5.0,70.0,34.2,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Brócolis Cozido','ramo médio',4.0,120.0,34.8,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Brócolis','ramo médio',4.0,120.0,34.8,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Cenoura Cozida','unidade média',1.0,75.0,33.8,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Cenoura Cozida','colher de sopa',6.0,78.0,35.1,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Cenoura Crua','unidade média',1.0,90.0,38.7,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Cogumelo Cozido','unidade média',11.0,132.0,35.6,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Couve Cozida','colher de sopa',3.0,105.0,33.6,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Molho de Tomate','colher de sopa',1.5,30.0,32.7,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Quiabo','unidade média',5.0,100.0,32.0,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Sopa de legumes','concha média',1.0,60.0,35.4,'vegetal-b');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Vagem','colher de sopa',6.0,96.0,33.6,'vegetal-b');

-- cereal-legume
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('All Bran', '¾ xícara', 0.7, 30.0, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Arroz Cozido', 'colher de sopa', 3.5, 70.0, 76.3, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Arroz Branco Coz. s/ sal', 'colher sopa', 3.5, 70.0, 76.3, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Arroz Integral', 'colher de sopa', 2.0, 60.0, 71.4, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Aveia', 'colher de sopa', 2.0, 22.0, 84.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Aveia Quaker sabor light', 'pacote', 0.5, 50.0, 70.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Batata Cozida s/ Casca', 'colher de sopa rasa', 3.5, 94.5, 81.3, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Batata Cozida s/ Casca s/ sal', 'colher de sopa cheia', 2.5, 97.5, 83.8, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Batata Doce Assada c/ Casca', 'colher de sopa cheia', 4.0, 80.0, 82.4, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Bolacha Cream Crackers', 'unidade média', 3.0, 19.5, 84.4, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Bolacha Água e Sal', 'unidade média', 2.5, 16.3, 73.9, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Bolo s/ Recheio e Cobertura', 'fatia média', 0.3, 22.9, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Broto de Feijão', 'concha média', 4.0, 240.0, 79.2, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Cogumelo Cru', 'unidade média', 18.0, 324.0, 81.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Cogumelo em Lata', 'unidade média', 28.0, 336.0, 80.6, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Cogumelo Murril', 'unidade', 2.0, 30.0, 71.3, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Cucuz de flocao kimilho', 'colher de sopa', 2.5, 20.8, 72.6, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Ervilha Verde Cozida', 'colher de sopa', 5.0, 100.0, 84.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Ervilha', 'colher de sopa', 6.0, 120.0, 82.8, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Farelo de Trigo', 'colher de sopa rasa', 6.0, 36.0, 77.8, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Farinha de Maracujá', 'colher de sopa', 4.0, 60.0, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Farinha de Milho', 'colher de sopa', 1.5, 22.5, 82.8, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Farinha de Rosca', 'colher de sopa', 1.5, 19.5, 76.4, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Farinha de Trigo', 'colher de sopa', 1.0, 20.0, 72.8, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Feijão Cozido só Caldo', 'copo americano', 5.0, 750.0, 83.3, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Feijão', 'colher de sopa', 4.0, 72.0, 84.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Fubá', 'colher de sopa', 1.5, 22.5, 81.9, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Gérmen de Trigo', 'colher de sopa rasa', 3.5, 21.0, 77.1, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Granola', 'colher de sopa', 1.0, 15.0, 66.8, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Granola - G. Flakes Jasmine', '¾ xícara', 0.5, 20.0, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Granola Receita Caseira', 'colher de sopa', 1.0, 15.0, 73.1, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Grão de Bico', 'concha média', 0.2, 22.0, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Inhame Cozido ou Assado', 'colher de sopa cheia', 2.0, 74.0, 85.8, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Lentilha', 'colher de sopa', 3.5, 77.0, 81.6, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Levedo de Cerveja', 'colher de sopa rasa', 1.3, 23.0, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Macarrão', 'escumadeira média', 0.5, 75.0, 83.3, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Macarrão Rilla (Vittafix) sem glúten', 'prato raso', 0.3, 27.2, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Maisena', 'colher de sopa', 1.5, 22.5, 81.5, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Mandioquinha', 'unidade média', 0.8, 98.8, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Mandioca cozida', 'pedaço pequeno', 1.0, 44.4, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Mel de Abelha', 'colher de sopa', 1.0, 26.0, 79.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Milho', 'colher de sopa', 3.5, 70.0, 75.6, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pão de Centeio', 'fatia média', 1.2, 30.5, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pão Integral', 'fatia media', 1.2, 30.0, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pão Integral Torrado', 'fatia media', 1.2, 27.6, 80.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pão Italiano', 'fatia media', 0.5, 32.5, 89.7, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pão Light Seven Boys', 'fatia media', 2.0, 42.0, 79.8, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pão Sírio', 'unidade', 1.0, 25.0, 72.5, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Purê de Batata Puro', 'colher de sopa', 1.5, 75.0, 79.5, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Quinua Real (Far/Grão/Floco)', 'colher sob cheia', 2.5, 25.0, 86.9, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Rosquinha integral jasmine', 'unidade', 4.0, 20.0, 82.0, 'cereal-legume');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Tapioca/tapioca sabor da paraíba', 'colher de sopa cheia', 1.5, 30, 75, 'cereal-legume');

-- carne-queijo
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Alcatra Magra Assada grelh', 'bife médio', 1.0, 90.0, 187.2, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Albumina', null, null, 54.7, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Almondega vegetariana - superbom', 'unidade', 8, 200, 212.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Atum Enlatado em Óleo', 'colher de sopa cheia', 6.5, 104.0, 204.9, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Bife de Filé Mignon', 'bife médio', 1.1, 107.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Blanquet Peru Light', 'fatia fina', 14.5, 232.0, 208.8, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Carne de Porco Assada', 'bisteca', 0.6, 60.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Carne de Porco Cozida', 'pedaço médio', 0.6, 56.6, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Carne de Porco Grelhada', 'bife médio', 0.7, 65.4, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Carne de Porco Magra ass', 'bife médio', 0.8, 76.6, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Carne de Porco Magra coz', 'pedaço médio', 0.7, 71.4, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Carne de Porco Magra grel', 'bife médio', 0.9, 82.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Carne Assad /Cozid Magra', 'fatia média', 1.5, 108.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Carne Bovina ref / Assada', 'fatia média', 1.0, 75.0, 216.2, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Carne Moída (PATINHO)', 'colher de sopa', 4.5, 114.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Churrasquinho', 'unidade', 1.75, 80.5, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Bife de Contra Filé Magro', 'bife médio', 1.1, 101.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Bife Coxão Mole Magro', 'bife médio', 1.2, 111.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Frango Assado', 'sobrecoxa', 2.0, 130.0, 214.5, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Frango', 'filé', 0.8, 100.4, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Kibe Assado', 'unidade', 5.0, 150.0, 217.5, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Clara de Ovo Cozida', 'unidade média', 11.5, 425.5, 207.4, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Ovo Cozido', 'unidade média', 2.6, 132.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Ovo Frito', 'unidade média', 2.5, 115.0, 207.2, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Ovo Poche', 'unidade média', 2.6, 133.5, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pato assado sem pele', null, null, 104.5, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Peixe', 'filé médio', 1.7, 214., 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Peito defumado frango perdigão', 'fatia', 6.5, 172.9, 207.5, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Peru Carne Branca Assada', 'fatia média', 5.0, 120.0, 204.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Peixe Gralhado / Cozido', 'fatia grossa', 0.8, 100.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Picanha s/capa de Gordura', 'fatia média', 1.1, 107.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Presunto de Peru Sadia', 'fatia média', 13.5, 202.5, 209.2, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Presunto Defumado Magro', 'fatia fina', 14.5, 145.0, 213.2, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Presunto Magro', 'fatia grossa', 2.1, 95.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Proteibar', 'tablete', 1.1, 110.5, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Cottage', 'colher de sopa', 7.0, 210.0, 202.7, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Minas', 'fatia média', 3.7, 56.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Minas Frescal', 'fatia média', 6.0, 90.0, 218.7, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Mussarela', 'fatia média', 5.0, 75.0, 211.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Mussarela Light', 'fatia média', 5.5, 82.5, 219.5, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Polenguinho', 'unidade', 3.5, 70.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Polenguinho Light', 'unidade', 5.5, 110.0, 212.3, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Prato ', 'fatia media', 2.5, 50.0, 201.3, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Prato Light', 'fatia media', 5.4, 109.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Provolone ', 'fatia media', 2.0, 60.0, 210.9, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Queijo Tofu', 'fatia media', 8.7, 217.6, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Salmão Cozido', 'filé médio', 1.5, 180.0, 210.6, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Salsicha de Frango', 'unidade', 1.6, 67.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Salsicha de Peru Light', 'unidade', 3.0, 126.0, 204.1, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Salsicha', 'unidade', 2.3, 69.0, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Salsicha vegetal', 'unidade', 3, 140, 210, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Salsicha Perdigão', 'unidade', 4.2, 89.7, 210.0, 'carne-queijo');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Sardinha Enlatada no Óleo', 'unidade media', 3.0, 102.0, 207.1, 'carne-queijo');

-- vegetal-a
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Abobrinha', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Acelga Cozida com Sal', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Acelga Crua', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Agrião', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Alface Americana', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Alface', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Almeirão', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Aspargo', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Chuchu Cozido', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Couve-Flor', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Escarola', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Espinafre', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Nabo', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pepino', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Pimentão', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Rabanete', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Repolho', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Salsão', null, null, null, null, 'vegetal-a');
insert into food(name, unit, amount_unit, amount_gram, amount_calories, uuid_food_group) values ('Tomate', null, null, null, null, 'vegetal-a');
